# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Αρχική"
  url = "#slider"
  weight = 10

[[main]]
  name = "Ο Καθηγητής"
  url = "#about"
  weight = 20

[[main]]
  name = "Δήλωση Ενδιαφέροντος"
  url = "#form"
  weight = 30

[[main]]
  name = "Επικοινωνία"
  url = "#contact"
  weight = 40

[[main]]
  name = "Συχνές ερωτήσεις"
  url = "/faq"
  weight = 50

[[main]]
  name = "Ιστολόγιο"
  url = "https://physiart.com"
  weight = 60

[[main_right]]
  name = "Είσοδος Μαθητή"
  pre = "<span class='btn btn-primary'><i class='fas fa-sign-in-alt'></i>&nbsp;"
  url = "https://moodle.physiart.com"
  post = "</span>"
  weight = 50

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
